#!/bin/bash

# This script converts certain gnu binutils objcopy arguments
# into llvm-objcopy arguments. Currently only -S (strip all)
# and -j (keep sections) are supported.

argv=($@)
argc=$#

for ((i=0; $i<$argc; i++)); do
  if [ "${argv[$i]}" = "-S" ]; then
    argv[$i]="-strip-all"
  elif [ "${argv[$i]}" = "-j" ]; then
    argv[$i]="-only-keep"
    i=$((i+1))
  elif [ "${argv[$i]}" = "-O" ]; then
    i=$((i+1))
    if [ "${argv[$i]}" != "binary" ]; then
      echo "llvm-objcopy cannot output to ${argv[$i]}"
      exit 1
    fi
  elif [[ "${argv[$i]}" == -* ]]; then
    echo "Unsupported argument ${argv[$i]}"
    exit 1
  fi
done

llvm-objcopy "${argv[@]}"
